# Introduction to Kafka

From the root of your repository:

## Deploy the `kafka-receiver` application:

*Remember to have the WORKSHOP_USER environment variable set appropriately*

[source,bash]
----
cd projects/kafka/kafka-receiver
mvn clean package
oc new-build --binary --name=kafka-receiver
oc start-build kafka-receiver --from-dir=. --follow
oc new-app kafka-receiver -e WORKSHOP_USER=$WORKSHOP_USER
oc expose svc/kafka-receiver
----

The application will take some minutes to deploy.

### Check the status of your applications

You can check the status of your projects on OpenShift using:

[source,bash]
----
oc status
----

### View the logs of your application

After your application is running, you can check the logs with:

[source,bash]
----
oc logs $(oc get po -o name -l app=kafka-receiver) -f
----

## Deploy the `kafka-sender` application:

[source,bash]
----
cd projects/kafka/kafka-sender
mvn clean package
oc new-build --binary --name=kafka-sender
oc start-build kafka-sender --from-dir=. --follow
oc new-app kafka-sender -e WORKSHOP_USER=$WORKSHOP_USER
----

The application will take some minutes to deploy.

### Check the status of your applications

You can check the status of your projects on OpenShift using:

[source,bash]
----
oc status
----

### View the logs of your application

After your application is running, you can check the logs with:

[source,bash]
----
oc logs $(oc get po -o name -l app=kafka-sender) -f
----

## List the Kafka topics on the broker

[source,bash]
----
oc exec -it my-cluster-kafka-0 -n strimzi-infra -c kafka -- bin/kafka-topics.sh --zookeeper localhost:2181 --describe
----

## Printing the messages on a Kafka topic

[source,bash]
----
oc exec -c zookeeper -it my-cluster-zookeeper-0 -n strimzi-infra -- /opt/kafka/bin/kafka-console-consumer.sh \
	--bootstrap-server my-cluster-kafka-bootstrap:9092 \
	--from-beginning \
	--property print.key=true \
	--topic my-topic-$WORKSHOP_USER
----
